version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - policy-intent-network

  redis:
    image: "redis:alpine"
    networks:
      - policy-intent-network

networks:
  policy-intent-network:
    driver: bridge
